boundless_lotus_press/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('autentificacion.urls')),
    url(r'^blog/', include('devblog.urls')),
    url(r'^draceditor/', include('draceditor.urls')),
    url(r'^', include('main.urls')),
]

main/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^', views.index, name='index'),
]

devblog/models.py
from django.db import models
from django.utils import timezone
from draceditor.models import DraceditorField


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    content = DraceditorField(default="")
    title = models.CharField(max_length=200)
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    # Create a property that returns the markdown instead
    @property
    def formatted_markdown(self):
        return self.content


class Comment(models.Model):
    post = models.ForeignKey('devblog.Post', related_name='comments')
    author = models.ForeignKey('auth.User')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

templates/principal/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">

    <title>Bouderless Lotus Press</title>


    {% block precss %}

    {% endblock %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <link rel="shortcut icon" type="image/png" href="{% static "images/logo.png" %}">
    <link rel="stylesheet" href="{% static "css/arreglos.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Overpass" rel="stylesheet">
    {% block css %}

    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.1.1.slim.js" integrity="sha256-5i/mQ300M779N2OVDrl16lbohwXNUdzL/R2aVUXyXWA=" crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.js" %}" type="text/javascript" charset="utf-8" async defer></script>
  </head>

  <body>
    <div class="page-wrap">
      <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/"><i class="fa fa-home" aria-hidden="true"></i> Home</a>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/team"><i class="fa fa-users" aria-hidden="true"></i> Development team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/projects"><i class="fa fa-list" aria-hidden="true"></i> Our rojects</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bookmark" aria-hidden="true"></i> Blog</a>
              <div class="dropdown-menu inverse-dropdown" aria-labelledby="dropdown01">
                {% if perms.blog.add_post %}
                  <a class="dropdown-item" href="/blog/addpost/"><i class="fa fa-plus-square-o" aria-hidden="true"></i> Add post</a>
                {% endif %}
                <a class="dropdown-item" href="/blog/page-1/"><i class="fa fa-th-list" aria-hidden="true"></i> All the posts</a>
                <!-- Listar a los autores que tengamos con un bucle-->
                <a class="dropdown-item" href="/blog/author-1/page-1/"><i class="fa fa-id-badge" aria-hidden="true"></i> Developer 1</a>
                <a class="dropdown-item" href="/blog/author-2/page-1/"><i class="fa fa-id-badge" aria-hidden="true"></i> Developer 2</a>
                <a class="dropdown-item" href="/blog/author-3/page-1/"><i class="fa fa-id-badge" aria-hidden="true"></i> Admin annoucements</a>
              </div>
            </li>
            {% if user.is_staff %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-wrench" aria-hidden="true"></i> Manage page</a>
              <div class="dropdown-menu inverse-dropdown" aria-labelledby="dropdown02">
                <a class="dropdown-item" href="/auth/users/page-1/">Manage authors</a>
                <a class="dropdown-item" href="/othermanageoptions">TBD</a>
              </div>
            </li>
            {% endif %}
          </ul>
          <div class="navbar-right" id="NavbarLogin">
              <ul class="navbar-nav mr-auto">
                  {% if user.is_authenticated %}
                    <li class="nav-item" ><a id="bienvenida" class="nav-link caret" href="/auth/profile/">Bienvenido, {{ user.username }}.</a></li> <li><a class="nav-link" href="/auth/logout/">Salir</a></li>
                  {% else %}<li class="nav-item"><a class="nav-link" href="/auth/login/">Entrar/Registrarse</a></li>{% endif %}
                  </ul>
          </div>
        </div>
      </nav>

      {% block content %}

      {% endblock  %}
</div>
    <div class="footer">
        <footer>
            <p>&copy; Black Tea Sails {% now 'Y' %} <a href="https://github.com/JoseAndNikita"><i class="fa fa-github" aria-hidden="true"></i> GitHub</a></p>
        </footer>
        </div> <!-- /container -->
    </div>
    
      <script src="https://cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js"></script>
    {% block js %}

    {% endblock %}

  </body>
</html>

templates/principal/profile.html
{% extends 'principal/shortpage.html' %}
{% load staticfiles %}

{% block morecss %}
<link rel="stylesheet" href="{% static "css/logreg.css" %}">
{% endblock morecss %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class=".card panel-login">
          <div class="card-header">
            <div class="row">
              <div class="col-sm-12">
                <h2 id="profile-update-form">Perfil de {{user_profile.username}}</h2>
              </div>
            </div>
            <hr>
          </div>
          <div class="card-block">
            <div class="row">
              <div class="col-lg-12">
                <form id="update-form" action="{{ prefix }}" method="post" role="form">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field }}
                        </div>
                    {% endfor %}

                    {% if user.is_staff %}
                    <div class="form-check">
                      <label class="form-check-label">
                        <input type="checkbox" name="is_author" id="is_author" tabindex="1" class="form-check-input">
                        Author permision.
                      </label>
                    </div>

                    <div class="form-check">
                      <label class="form-check-label">
                        <input type="checkbox" name="is_personal" id="is_personal" tabindex="2" class="form-check-input">
                        Is internal personal.
                      </label>
                    </div>
                    {% endif %}

                    {% if field.errors %}
                    <div class="alert alert-dismissible alert-warning" id="registration_error">
                      <button type="button" class="close" data-dismiss="alert">&times;</button>

                      {{ field.errors }}
                      {% if field.help_text %}
                      <p class="help">{{ field.help_text|safe }}</p>
                      {% endif %}
                      </div>
                    {% endif %}


                    <!-- Zona del mensaje error -->
                    {% if messages %}
                      {% for message in messages %}
                      {% if message.tags %}
                        <div  class="alert alert-{{ message.tags }} alert-dismissible" id="modification-{{ message.tags }}">
                      {% endif %}
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          {{ message|safe }}</div>
                      {% endfor %}
                    {% endif %}
                      <!-- Fin Zona del mensaje error -->

                    <div class="form-group">
                      <div class="row">
                        <div class="col-sm-6 offset-sm-3">
                          <input type="submit" name="update-submit" id="update-submit" tabindex="4" class="form-control btn btn-success" value="Actualizar">
                        </div>
                      </div>
                    </div>
                </form>
                {% if user.is_staff or prefix == '/auth/profile/' %}
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-6 offset-sm-3">
                    <a href="/auth/change_pass/" class="form-control btn btn-warning" role="button" aria-pressed="true">Change password</a>
                  </div>
                </div>
</div>

                <div class="row">
                  <div class="col-sm-6 offset-sm-3">
                    <a href="{% url 'remove_user' user_id=user_profile.id %}" class="form-control btn btn-danger" role="button" aria-pressed="true">Delete user</a>
                  </div>
                </div>
                {% endif %}

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content%}

{% block js %}

{% endblock js %}

templates/principal/shortpage.html
{% extends 'principal/base.html' %}
{% load staticfiles %}

{% block css %}

  {% block morecss %}
  {% endblock %}
    <link rel="stylesheet" href="{% static "css/shortpage.css" %}">
{% endblock css %}